# Generated by Django 2.2.14 on 2023-06-05 09:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
