# Generated by Django 2.2.14 on 2023-06-05 10:13

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230605_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_available',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=500)),
        ),
        migrations.AlterField(
            model_name='book',
            name='follow_author',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=2083)),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=django_cryptography.fields.encrypt(models.CharField(default=False, max_length=2083)),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=django_cryptography.fields.encrypt(models.FloatField(blank=True, null=True)),
        ),
    ]
